name: Update README Status

on:
  push:
    paths:
      - "data/**"
  schedule:
    - cron: "0 * * * *" # every hour check/update
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install pandas pytz

      - name: Update README status fields
        run: |
          python update_readme_status_fields.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'xdc-intel-bot'
          git config --global user.email 'intelbot@xdc.org'
          git add README.md
          git commit -m "Auto-refresh: Updated system status after scans"
          git push
